### ISSUE TITLE
https://sandstorm.io page, does "60 second demo" mean 60 minutes?

### ISSUE THREAD

**Issue by xet7** [sandstorm-io/sandstorm-website#143]
Hi,
when I'm at https://sandstorm.io page, and click "60 second demo", it looks like demo is running for 60 minutes, according to counter?

BR,
xet7

**Comment by ocdtrekkie** [comment]
It's supposed to take sixty seconds to see how it works, but you can use the demo account for up to sixty minutes. 

That's an interesting/useful point though, that people might connect those two numbers.

**Comment by kentonv** [comment]
Hi @xet7,

Jake is correct, the "60 second" in the button title is not meant to have anything to do with the time limit, it's just a coincidence. A few people have pointed this out now, so maybe we should change the button text to avoid throwing people off.

The problem we were trying to solve is that a lot of people don't click the demo button because they think a demo will take a while. We wanted to communicate that it doesn't take long to see how Sandstorm works, and that this is actually the fastest way to understand it.

**Comment by frewsxcv** [comment]
For what it's worth, I was just about to report this same issue as I thought it was a bug

**Comment by neynah** [comment]
@frewsxcv @xet7 I agree this is confusing. I've submitted a fix in #147 so the text now says "Try a Quick Demo." Let me know if this is more clear (there's a screenshot in the pull request).

**Comment by xet7** [comment]
@neynah Thanks, that looks great! :)

**Comment by kentonv** [comment]
Fix pushed!
